export type MediaType = "movie" | "tv";
export type MoodTag =
  | "mind-bending" | "cozy" | "dark" | "funny" | "sad" | "epic"
  | "romantic" | "action" | "thriller" | "sci-fi" | "fantasy"
  | "slow-burn" | "fast-paced" | "short" | "binge" | "iconic" | "hidden-gem";

export interface CatalogItem {
  id: string;
  tmdb_id: number;
  type: MediaType;
  title: string;
  year: number;
  rating: number;         // 0-10
  popularity: number;     // 0-100
  runtimeMin?: number;    // per episodio o film
  seasons?: number;
  genres: string[];
  moods: MoodTag[];
  overview: string;
  poster: string;         // gradient placeholder o url() CSS
  posterUrl?: string | null;
  backdropUrl?: string | null;
  where?: string[];
  similar?: string[];
}

// helper poster (colored gradient placeholder)
const g = (from: string, to: string) =>
  `linear-gradient(135deg, ${from}, ${to})`;

export const CATALOG: CatalogItem[] = [
  { id:"severance", tmdb_id:95396, type:"tv", title:"Severance", year:2022, rating:8.7, popularity:92, runtimeMin:55, seasons:2,
    genres:["Sci-Fi","Thriller","Drama"], moods:["mind-bending","dark","slow-burn","binge","thriller","sci-fi"],
    overview:"Impiegati che scindono i ricordi tra lavoro e vita privata. Poi qualcosa si rompe.",
    poster:g("#3b1361","#0ea5e9"), where:["Apple TV+"], similar:["dark","black-mirror","mr-robot"] },
  { id:"dark", tmdb_id:70523, type:"tv", title:"Dark", year:2017, rating:8.8, popularity:88, runtimeMin:55, seasons:3,
    genres:["Sci-Fi","Mystery","Thriller"], moods:["mind-bending","dark","slow-burn","binge","sci-fi"],
    overview:"Un paesino tedesco, quattro famiglie e un buco temporale. Portate un blocco per appunti.",
    poster:g("#0b132b","#5bc0be"), where:["Netflix"], similar:["severance","1899"] },
  { id:"black-mirror", tmdb_id:42009, type:"tv", title:"Black Mirror", year:2011, rating:8.3, popularity:85, runtimeMin:60,
    genres:["Sci-Fi","Drama","Anthology"], moods:["mind-bending","dark","short","sci-fi","iconic"],
    overview:"Antologia distopica sulla tecnologia. Vi farà spegnere il telefono. Per 5 minuti.",
    poster:g("#111","#7f1d1d"), where:["Netflix"], similar:["severance","mr-robot"] },
  { id:"mr-robot", tmdb_id:62560, type:"tv", title:"Mr. Robot", year:2015, rating:8.5, popularity:78, runtimeMin:50, seasons:4,
    genres:["Thriller","Drama","Crime"], moods:["mind-bending","dark","binge","thriller"],
    overview:"Un hacker socialmente inetto vuole abbattere la corporazione più potente del mondo.",
    poster:g("#0f0f0f","#dc2626"), where:["Prime Video"], similar:["severance","black-mirror"] },
  { id:"the-office", tmdb_id:2316, type:"tv", title:"The Office", year:2005, rating:8.9, popularity:95, runtimeMin:22, seasons:9,
    genres:["Comedy"], moods:["funny","cozy","binge","iconic"],
    overview:"Un mockumentary in un ufficio di carta. È stranamente terapeutico.",
    poster:g("#1e3a8a","#93c5fd"), where:["Prime Video","Netflix"], similar:["parks-and-rec","brooklyn99"] },
  { id:"parks-and-rec", tmdb_id:8592, type:"tv", title:"Parks and Recreation", year:2009, rating:8.6, popularity:80, runtimeMin:22, seasons:7,
    genres:["Comedy"], moods:["funny","cozy","binge"],
    overview:"Burocrazia municipale ma con più waffle.",
    poster:g("#065f46","#fbbf24"), similar:["the-office","brooklyn99"] },
  { id:"brooklyn99", tmdb_id:48891, type:"tv", title:"Brooklyn Nine-Nine", year:2013, rating:8.4, popularity:82, runtimeMin:22, seasons:8,
    genres:["Comedy","Crime"], moods:["funny","cozy","binge"],
    overview:"Polizia di quartiere, meme e Terry ama lo yogurt.",
    poster:g("#7c2d12","#f59e0b"), similar:["parks-and-rec","the-office"] },
  { id:"game-of-thrones", tmdb_id:1399, type:"tv", title:"Game of Thrones", year:2011, rating:8.4, popularity:99, runtimeMin:60, seasons:8,
    genres:["Fantasy","Drama"], moods:["epic","dark","fantasy","binge","iconic"],
    overview:"Draghi, tradimenti, matrimoni ad alto rischio. Il finale lo abbiamo rimosso.",
    poster:g("#450a0a","#d4a373"), similar:["house-of-dragon","lotr"] },
  { id:"house-of-dragon", tmdb_id:94997, type:"tv", title:"House of the Dragon", year:2022, rating:8.4, popularity:90,
    genres:["Fantasy","Drama"], moods:["epic","dark","fantasy","binge"], seasons:2,
    overview:"Targaryen contro Targaryen. Spoiler: draghi.",
    poster:g("#1c1917","#b91c1c"), similar:["game-of-thrones","lotr"] },
  { id:"the-bear", tmdb_id:136315, type:"tv", title:"The Bear", year:2022, rating:8.6, popularity:87, runtimeMin:30, seasons:3,
    genres:["Drama","Comedy"], moods:["fast-paced","dark","short","binge"],
    overview:"Cucina in rovina, ansia da prestazione, panini. Ideale per farsi venire la tachicardia.",
    poster:g("#7f1d1d","#fde68a"), similar:["succession","mad-men"] },
  { id:"succession", tmdb_id:76331, type:"tv", title:"Succession", year:2018, rating:8.9, popularity:83, runtimeMin:60, seasons:4,
    genres:["Drama"], moods:["dark","slow-burn","binge","iconic"],
    overview:"Fratelli miliardari si contendono un impero. Nessuno merita di vincere.",
    poster:g("#111827","#6b7280"), similar:["mad-men","the-bear"] },
  { id:"friends", tmdb_id:1668, type:"tv", title:"Friends", year:1994, rating:8.4, popularity:97, runtimeMin:22, seasons:10,
    genres:["Comedy","Romance"], moods:["cozy","funny","binge","romantic","iconic"],
    overview:"Sei amici, un divano, un appartamento improbabile a Manhattan.",
    poster:g("#6b21a8","#fde68a"), similar:["the-office","how-i-met-your-mother"] },
  { id:"stranger-things", tmdb_id:66732, type:"tv", title:"Stranger Things", year:2016, rating:8.6, popularity:96,
    genres:["Sci-Fi","Fantasy","Horror"], moods:["binge","fantasy","sci-fi","iconic"], seasons:4,
    overview:"Bambini, biciclette, mostri e nostalgia anni '80.",
    poster:g("#1e1b4b","#dc2626"), similar:["dark","black-mirror"] },
  { id:"arcane", tmdb_id:94605, type:"tv", title:"Arcane", year:2021, rating:9.0, popularity:88, seasons:2,
    genres:["Animation","Sci-Fi","Fantasy"], moods:["epic","dark","fantasy","binge","iconic"],
    overview:"Due sorelle, una città spezzata, animazione da premio Oscar.",
    poster:g("#312e81","#22d3ee"), similar:["cyberpunk-edgerunners","spider-verse"] },
  { id:"cyberpunk-edgerunners", tmdb_id:105248, type:"tv", title:"Cyberpunk: Edgerunners", year:2022, rating:8.6, popularity:75,
    genres:["Animation","Sci-Fi"], moods:["fast-paced","dark","short","binge","sci-fi"], seasons:1,
    overview:"Night City in 10 episodi. Portare fazzoletti.",
    poster:g("#0f172a","#f472b6"), similar:["arcane"] },
  { id:"inception", tmdb_id:27205, type:"movie", title:"Inception", year:2010, rating:8.4, popularity:92, runtimeMin:148,
    genres:["Sci-Fi","Action","Thriller"], moods:["mind-bending","action","sci-fi","iconic"],
    overview:"Sogni dentro sogni dentro sogni. La trottola gira ancora.",
    poster:g("#1e293b","#0891b2"), similar:["interstellar","tenet"] },
  { id:"interstellar", tmdb_id:157336, type:"movie", title:"Interstellar", year:2014, rating:8.6, popularity:94, runtimeMin:169,
    genres:["Sci-Fi","Drama","Adventure"], moods:["mind-bending","epic","sad","sci-fi","iconic"],
    overview:"Papà, non piangere. (Piange).",
    poster:g("#0c0a09","#a3a3a3"), similar:["inception","arrival"] },
  { id:"arrival", tmdb_id:329865, type:"movie", title:"Arrival", year:2016, rating:7.9, popularity:70, runtimeMin:116,
    genres:["Sci-Fi","Drama"], moods:["mind-bending","slow-burn","sad","sci-fi"],
    overview:"Alieni arrivano. Nessuno li capisce. Nemmeno voi capirete tutto al primo giro.",
    poster:g("#374151","#8b5cf6"), similar:["interstellar","inception"] },
  { id:"lotr", tmdb_id:120, type:"movie", title:"Il Signore degli Anelli: La Compagnia dell'Anello", year:2001, rating:8.4, popularity:95, runtimeMin:178,
    genres:["Fantasy","Adventure"], moods:["epic","fantasy","iconic","binge"],
    overview:"Frodo va a fare una passeggiata. Molto lunga.",
    poster:g("#1c1917","#84cc16"), similar:["house-of-dragon","game-of-thrones"] },
  { id:"spirited-away", tmdb_id:129, type:"movie", title:"La città incantata", year:2001, rating:8.5, popularity:80, runtimeMin:125,
    genres:["Animation","Family","Fantasy"], moods:["cozy","fantasy","iconic","sad"],
    overview:"Una bambina, un mondo di spiriti, cibo animato in modo indecente.",
    poster:g("#065f46","#fda4af"), similar:["princess-mononoke"] },
  { id:"princess-mononoke", tmdb_id:128, type:"movie", title:"Principessa Mononoke", year:1997, rating:8.4, popularity:65, runtimeMin:134,
    genres:["Animation","Fantasy","Adventure"], moods:["epic","fantasy","sad"],
    overview:"Ghibli, ma con più cinghiali arrabbiati.",
    poster:g("#14532d","#f97316"), similar:["spirited-away"] },
  { id:"spider-verse", tmdb_id:324857, type:"movie", title:"Spider-Man: Un nuovo universo", year:2018, rating:8.4, popularity:88, runtimeMin:117,
    genres:["Animation","Action"], moods:["fast-paced","funny","action","iconic"],
    overview:"Multiverso, colori, un ragno per tutti.",
    poster:g("#7f1d1d","#f43f5e"), similar:["arcane","across-the-spider-verse"] },
  { id:"across-the-spider-verse", tmdb_id:569094, type:"movie", title:"Across the Spider-Verse", year:2023, rating:8.6, popularity:92, runtimeMin:140,
    genres:["Animation","Action"], moods:["fast-paced","action","epic"],
    overview:"Ancora più ragni. Cliffhanger cattivissimo.",
    poster:g("#4c1d95","#f472b6"), similar:["spider-verse","arcane"] },
  { id:"everything-everywhere", tmdb_id:545611, type:"movie", title:"Everything Everywhere All at Once", year:2022, rating:8.0, popularity:82, runtimeMin:139,
    genres:["Sci-Fi","Comedy","Action"], moods:["mind-bending","funny","sad","action"],
    overview:"Una signora, un multiverso e delle patatine spiritose.",
    poster:g("#4c1d95","#22d3ee"), similar:["spider-verse","inception"] },
  { id:"her", tmdb_id:152601, type:"movie", title:"Her", year:2013, rating:8.0, popularity:60, runtimeMin:126,
    genres:["Romance","Drama","Sci-Fi"], moods:["sad","romantic","slow-burn","sci-fi"],
    overview:"Un uomo si innamora del sistema operativo. Nel 2013 sembrava assurdo.",
    poster:g("#7c2d12","#fecaca"), similar:["arrival"] },
  { id:"la-la-land", tmdb_id:313369, type:"movie", title:"La La Land", year:2016, rating:7.9, popularity:78, runtimeMin:128,
    genres:["Romance","Musical","Drama"], moods:["romantic","sad","cozy","iconic"],
    overview:"Sogni, jazz, un finale che ancora fa male.",
    poster:g("#1e40af","#facc15"), similar:["her"] },
  { id:"mad-max-fury-road", tmdb_id:76341, type:"movie", title:"Mad Max: Fury Road", year:2015, rating:8.1, popularity:80, runtimeMin:120,
    genres:["Action","Sci-Fi"], moods:["fast-paced","action","iconic"],
    overview:"Due ore di inseguimento nel deserto. Poesia.",
    poster:g("#7c2d12","#ea580c"), similar:["mad-max"] },
  { id:"john-wick", tmdb_id:245891, type:"movie", title:"John Wick", year:2014, rating:7.4, popularity:85, runtimeMin:101,
    genres:["Action","Thriller"], moods:["fast-paced","action","short"],
    overview:"Non toccategli il cane.",
    poster:g("#0a0a0a","#a78bfa"), similar:["mad-max-fury-road"] },
  { id:"the-menu", tmdb_id:593643, type:"movie", title:"The Menu", year:2022, rating:7.2, popularity:70, runtimeMin:107,
    genres:["Thriller","Comedy","Horror"], moods:["thriller","dark","funny","short"],
    overview:"Cena stellata. Cliente non soddisfatto.",
    poster:g("#111","#f59e0b"), similar:["glass-onion"] },
  { id:"glass-onion", tmdb_id:661374, type:"movie", title:"Glass Onion", year:2022, rating:7.2, popularity:78, runtimeMin:139,
    genres:["Mystery","Comedy","Crime"], moods:["funny","thriller","cozy"],
    overview:"Detective Blanc torna. Miliardari nei guai.",
    poster:g("#1e3a8a","#f472b6"), similar:["knives-out","the-menu"] },
  { id:"knives-out", tmdb_id:546554, type:"movie", title:"Knives Out", year:2019, rating:7.9, popularity:82, runtimeMin:130,
    genres:["Mystery","Comedy","Crime"], moods:["funny","thriller","cozy","iconic"],
    overview:"Whodunit moderno con maglioni indimenticabili.",
    poster:g("#3f0d0d","#eab308"), similar:["glass-onion"] },
  { id:"chernobyl", tmdb_id:87108, type:"tv", title:"Chernobyl", year:2019, rating:9.4, popularity:78, runtimeMin:60, seasons:1,
    genres:["Drama","History"], moods:["dark","short","slow-burn","sad","iconic"],
    overview:"5 episodi. Vi farà odiare l'energia nucleare o gli errori umani. O entrambi.",
    poster:g("#0f172a","#eab308"), similar:["succession"] },
  { id:"peaky-blinders", tmdb_id:60574, type:"tv", title:"Peaky Blinders", year:2013, rating:8.7, popularity:87, runtimeMin:55, seasons:6,
    genres:["Crime","Drama"], moods:["dark","binge","iconic"],
    overview:"Berretti taglienti, sguardi ancora di più.",
    poster:g("#1c1917","#78350f"), similar:["mad-men","succession"] },
  { id:"mad-men", tmdb_id:1104, type:"tv", title:"Mad Men", year:2007, rating:8.7, popularity:70, runtimeMin:47, seasons:7,
    genres:["Drama"], moods:["slow-burn","dark","binge","iconic"],
    overview:"Pubblicitari, whisky e sigarette. Alcuni sentimenti, occasionalmente.",
    poster:g("#111827","#f97316"), similar:["succession","peaky-blinders"] },
  { id:"fleabag", tmdb_id:67070, type:"tv", title:"Fleabag", year:2016, rating:8.7, popularity:70, runtimeMin:27, seasons:2,
    genres:["Comedy","Drama"], moods:["funny","sad","short","iconic"],
    overview:"Rompe la quarta parete e anche voi.",
    poster:g("#450a0a","#f43f5e"), similar:["the-bear","succession"] },
  { id:"how-i-met-your-mother", tmdb_id:1100, type:"tv", title:"How I Met Your Mother", year:2005, rating:8.3, popularity:75, runtimeMin:22, seasons:9,
    genres:["Comedy","Romance"], moods:["cozy","funny","binge","romantic"],
    overview:"9 stagioni per raccontare una storia. Anche noi non le abbiamo dimenticate.",
    poster:g("#0f766e","#fde68a"), similar:["friends"] },
  { id:"1899", tmdb_id:90669, type:"tv", title:"1899", year:2022, rating:7.6, popularity:60, runtimeMin:60, seasons:1,
    genres:["Mystery","Sci-Fi"], moods:["mind-bending","dark","slow-burn","sci-fi"],
    overview:"Un piroscafo, tanti misteri. Cancellata prima del finale (piangiamo).",
    poster:g("#0c4a6e","#a3a3a3"), similar:["dark","severance"] },
  { id:"witcher", tmdb_id:71912, type:"tv", title:"The Witcher", year:2019, rating:8.0, popularity:82, runtimeMin:55, seasons:3,
    genres:["Fantasy","Action"], moods:["epic","fantasy","action","binge"],
    overview:"Toss a coin. Please.",
    poster:g("#1c1917","#22d3ee"), similar:["witcher","house-of-dragon"] },
  { id:"tenet", tmdb_id:577922, type:"movie", title:"Tenet", year:2020, rating:7.3, popularity:70, runtimeMin:150,
    genres:["Action","Sci-Fi","Thriller"], moods:["mind-bending","action","sci-fi","fast-paced"],
    overview:"Va avanti? Va indietro? Sì.",
    poster:g("#111827","#0ea5e9"), similar:["inception","interstellar"] },
  { id:"pulp-fiction", tmdb_id:680, type:"movie", title:"Pulp Fiction", year:1994, rating:8.5, popularity:88, runtimeMin:154,
    genres:["Crime","Drama"], moods:["iconic","dark","funny","fast-paced"],
    overview:"Cheeseburger, valigette e monologhi biblici.",
    poster:g("#0a0a0a","#f59e0b"), similar:["glass-onion"] },
];

export function findById(id: string) {
  return CATALOG.find(c => c.id === id);
}
