import type { NerdacoloQuestion, ScoringEffects } from "./nerdacolo-types";

function fx(effects: ScoringEffects) {
  return effects;
}

/** Pool domande Nerdacolo — ordine scelto dinamicamente dal engine, non fisso. */
export const NERDACOLO_QUESTIONS: NerdacoloQuestion[] = [
  {
    id: "mood-night",
    category: "mood",
    text: "Che tipo di serata è?",
    subtitle: "Nerdacolo annusa l'atmosfera del divano.",
    appliesTo: "both",
    priority: 10,
    maxAskOnce: true,
    discriminates: ["mood", "emotionalImpact", "comedyLevel"],
    options: [
      { id: "cozy", label: "Divano, coperta e zero traumi", funnyReaction: "Il tuo divano ha sospirato di sollievo.", effects: fx({ boostTraits: { comfortLevel: 2, comedyLevel: 1, emotionalImpact: -1 }, boostMoods: ["cozy", "funny"], penalizeTraits: { horrorLevel: -2, violenceLevel: -2 } }) },
      { id: "laugh", label: "Voglio ridere senza usare troppi neuroni", funnyReaction: "Neuroni risparmiati. Nerdacolo approva.", effects: fx({ boostTraits: { comedyLevel: 2, complexity: -1 }, boostMoods: ["funny"], penalizeTraits: { complexity: -1, emotionalImpact: -1 } }) },
      { id: "mystery", label: "Voglio mistero e sospetti su chiunque", funnyReaction: "Nessuno è innocente finché Nerdacolo non dice il contrario.", effects: fx({ boostTraits: { mysteryLevel: 2, complexity: 1 }, boostMoods: ["thriller", "mind-bending"], penalizeTraits: { comedyLevel: -1 } }) },
      { id: "cry", label: "Voglio farmi distruggere emotivamente", funnyReaction: "Fazzoletti pronti. La sfera non giudica.", effects: fx({ boostTraits: { emotionalImpact: 2, romanceLevel: 1 }, boostMoods: ["sad", "romantic"], penalizeTraits: { comedyLevel: -2 } }) },
      { id: "action", label: "Voglio azione, ritmo e casino", funnyReaction: "Modalità popcorn attivata.", effects: fx({ boostTraits: { pace: 2, visualSpectacle: 2 }, boostMoods: ["action", "fast-paced"], penalizeTraits: { pace: -1 } }) },
      { id: "weird", label: "Voglio qualcosa di strano, ma bello", funnyReaction: "La sfera ama le chicche bizzarre.", effects: fx({ boostTraits: { complexity: 1, mainstreamLevel: -1 }, boostMoods: ["mind-bending", "sci-fi"], softFilters: { preferDiscovery: 2 } }) },
    ],
  },
  {
    id: "energy-brain",
    category: "energy",
    text: "Quanti neuroni hai disponibili stasera?",
    appliesTo: "both",
    priority: 9,
    maxAskOnce: true,
    discriminates: ["complexity", "pace"],
    options: [
      { id: "two", label: "Due, e stanno litigando", funnyReaction: "Plot semplice incoming.", effects: fx({ boostTraits: { complexity: -2, comedyLevel: 1 }, hardFilters: { maxComplexity: "easy" } }) },
      { id: "normal", label: "Abbastanza per seguire una trama normale", funnyReaction: "Trama normale = già un lusso.", effects: fx({ boostTraits: { complexity: 0 } }) },
      { id: "conspiracy", label: "Sono pronto per complotti, timeline e lavagne", funnyReaction: "Nerdacolo prepara lavagna e timeline.", effects: fx({ boostTraits: { complexity: 2, mysteryLevel: 1 }, boostMoods: ["mind-bending"] }) },
      { id: "elegant", label: "Fammi soffrire, ma con eleganza", funnyReaction: "Sofferenza con buona fotografia, coming up.", effects: fx({ boostTraits: { complexity: 1, emotionalImpact: 2, visualSpectacle: 1 } }) },
    ],
  },
  {
    id: "time-movie",
    category: "time",
    text: "Quanto tempo vuoi investire?",
    appliesTo: "movie",
    priority: 9,
    maxAskOnce: true,
    discriminates: ["commitment"],
    options: [
      { id: "90", label: "Massimo 90 minuti", funnyReaction: "Ho scartato i film che richiedono un intervallo.", effects: fx({ hardFilters: { maxRuntimeMinutes: 110 }, boostTraits: { commitment: -2 } }) },
      { id: "120", label: "Anche 2 ore va bene", funnyReaction: "Serata classica da cinema.", effects: fx({ boostTraits: { commitment: 0 } }) },
      { id: "180", label: "Pure 3 ore, ma deve meritare", funnyReaction: "Solo epici degni del tuo tempo.", effects: fx({ boostTraits: { commitment: 2, visualSpectacle: 1 }, hardFilters: { minRuntimeMinutes: 130 } }) },
      { id: "decide", label: "Non lo so, decidi tu", funnyReaction: "Ok, comando accettato.", effects: fx({}) },
    ],
  },
  {
    id: "time-tv",
    category: "time",
    text: "Quanto tempo vuoi investire?",
    appliesTo: "tv",
    priority: 9,
    maxAskOnce: true,
    discriminates: ["commitment", "bingeability"],
    options: [
      { id: "one-ep", label: "Una puntata e dormo", funnyReaction: "Un episodio, promesso. (Nerdacolo mente spesso.)", effects: fx({ boostTraits: { commitment: -2, bingeability: -1 }, hardFilters: { maxCommitment: "short" } }) },
      { id: "few-eps", label: "2-3 episodi", funnyReaction: "Giusto il giusto binge.", effects: fx({ boostTraits: { bingeability: 1 } }) },
      { id: "addiction", label: "Voglio iniziare una dipendenza", funnyReaction: "Ho scartato le serie da 12 stagioni. Scherzo. Forse.", effects: fx({ boostTraits: { bingeability: 2 }, boostMoods: ["binge"], softFilters: { preferBinge: 2 } }) },
      { id: "miniseries", label: "Cerco una miniserie", funnyReaction: "Storie chiuse, zero mutui emotivi.", effects: fx({ hardFilters: { maxSeasons: 2, maxCommitment: "short" }, boostTraits: { commitment: -2 } }) },
    ],
  },
  {
    id: "comfort-zone",
    category: "comfort",
    text: "Vuoi qualcosa vicino ai tuoi gusti o vuoi rischiare?",
    appliesTo: "both",
    priority: 8,
    maxAskOnce: true,
    discriminates: ["comfortLevel", "mainstreamLevel"],
    options: [
      { id: "total", label: "Comfort zone totale", funnyReaction: "Nessun salto nel vuoto stasera.", effects: fx({ boostTraits: { comfortLevel: 2 }, softFilters: { preferComfort: 3 } }) },
      { id: "similar", label: "Simile, ma con qualcosa di nuovo", funnyReaction: "Mezzo passo fuori zona.", effects: fx({ boostTraits: { comfortLevel: 1 }, softFilters: { preferDiscovery: 1 } }) },
      { id: "surprise", label: "Sorprendimi", funnyReaction: "La sfera si scalda.", effects: fx({ softFilters: { preferDiscovery: 2 }, penalizeTraits: { comfortLevel: -1 } }) },
      { id: "far", label: "Portami lontano, ma non farmi pentire", funnyReaction: "Rischio calibrato. Mi piace.", effects: fx({ softFilters: { preferDiscovery: 3 }, boostTraits: { mainstreamLevel: -1 }, penalizeTraits: { horrorLevel: -1 } }) },
    ],
  },
  {
    id: "darkness",
    category: "violence",
    text: "Quanto buio sopporti?",
    appliesTo: "both",
    priority: 8,
    maxAskOnce: true,
    discriminates: ["violenceLevel", "horrorLevel", "emotionalImpact"],
    options: [
      { id: "light", label: "Luce accesa e lieto fine", funnyReaction: "Niente incubi stanotte.", effects: fx({ hardFilters: { maxViolence: "low", maxHorror: "none" }, boostTraits: { emotionalImpact: -1 } }) },
      { id: "tension", label: "Un po' di tensione ci sta", funnyReaction: "Thriller soft, coming up.", effects: fx({ boostTraits: { mysteryLevel: 1 }, hardFilters: { maxHorror: "low" } }) },
      { id: "thriller", label: "Thriller, ansia, gente ambigua", funnyReaction: "Fidati di nessuno.", effects: fx({ boostTraits: { mysteryLevel: 2, violenceLevel: 1 }, boostMoods: ["thriller", "dark"] }) },
      { id: "destroy", label: "Distruggimi pure", funnyReaction: "La sfera ha messo le cuffie dark.", effects: fx({ boostTraits: { violenceLevel: 2, horrorLevel: 1, emotionalImpact: 2 }, boostMoods: ["dark"] }) },
    ],
  },
  {
    id: "pace",
    category: "pace",
    text: "Che ritmo vuoi?",
    appliesTo: "both",
    priority: 7,
    maxAskOnce: true,
    discriminates: ["pace"],
    options: [
      { id: "slow", label: "Lento ma profondo", funnyReaction: "Niente fretta, solo vibes.", effects: fx({ boostTraits: { pace: -2 }, boostMoods: ["slow-burn"] }) },
      { id: "balanced", label: "Equilibrato", funnyReaction: "Goldilocks zone.", effects: fx({ boostTraits: { pace: 0 } }) },
      { id: "fast", label: "Veloce, devo dire 'ancora uno'", funnyReaction: "Ritmo che non perdona.", effects: fx({ boostTraits: { pace: 2 }, boostMoods: ["fast-paced", "binge"] }) },
      { id: "chaos", label: "Caos, colpi di scena e zero pause", funnyReaction: "Attacchini di adrenalina.", effects: fx({ boostTraits: { pace: 2, complexity: 1 }, boostMoods: ["action", "fast-paced"] }) },
    ],
  },
  {
    id: "mainstream",
    category: "mainstream",
    text: "Vuoi andare sul sicuro o fare il fenomeno con una chicca?",
    appliesTo: "both",
    priority: 7,
    maxAskOnce: true,
    discriminates: ["mainstreamLevel"],
    options: [
      { id: "safe", label: "Mainstream, non voglio rischiare", funnyReaction: "Titoli che tutti conoscono (per un motivo).", effects: fx({ boostTraits: { mainstreamLevel: 2 }, hardFilters: { minMainstream: "balanced" } }) },
      { id: "quality", label: "Qualità ma non troppo sconosciuta", funnyReaction: "Il sweet spot del Nerdacolo.", effects: fx({ boostTraits: { mainstreamLevel: 0 } }) },
      { id: "gem", label: "Chicca nascosta", funnyReaction: "Cerco perle sottovalutate.", effects: fx({ boostTraits: { mainstreamLevel: -2 }, boostMoods: ["hidden-gem"] }) },
      { id: "weird-hit", label: "Titolo assurdo che poi consiglierò a tutti", funnyReaction: "Il consiglio che nessuno chiedeva.", effects: fx({ boostTraits: { mainstreamLevel: -1, complexity: 1 }, softFilters: { preferDiscovery: 2 } }) },
    ],
  },
  {
    id: "fantasy",
    category: "genre",
    text: "Quanto deve essere normale il mondo?",
    appliesTo: "both",
    priority: 6,
    maxAskOnce: true,
    discriminates: ["mood"],
    options: [
      { id: "real", label: "Realistico", funnyReaction: "Niente draghi, solo drama.", effects: fx({ penalizeMoods: ["fantasy", "sci-fi"], boostMoods: ["slow-burn"] }) },
      { id: "weird-real", label: "Realistico ma con stranezze", funnyReaction: "Slightly unhinged.", effects: fx({ boostMoods: ["mind-bending"], boostTraits: { mysteryLevel: 1 } }) },
      { id: "sf", label: "Fantascienza/fantasy ok", funnyReaction: "Spazio e magia benvenuti.", effects: fx({ boostMoods: ["sci-fi", "fantasy"], boostTraits: { visualSpectacle: 1 } }) },
      { id: "all-in", label: "Multiversi, mostri, magie, tutto dentro", funnyReaction: "Modalità lore infinita.", effects: fx({ boostMoods: ["fantasy", "sci-fi", "epic"], boostTraits: { visualSpectacle: 2 } }) },
    ],
  },
  {
    id: "social",
    category: "socialContext",
    text: "Con chi guardi?",
    appliesTo: "both",
    priority: 5,
    maxAskOnce: true,
    discriminates: ["comedyLevel", "horrorLevel"],
    options: [
      { id: "solo", label: "Da solo", funnyReaction: "Zero compromessi.", effects: fx({}) },
      { id: "couple", label: "In coppia", funnyReaction: "Niente troppo traumatico, forse.", effects: fx({ boostTraits: { romanceLevel: 1, comedyLevel: 1 }, hardFilters: { maxHorror: "medium" } }) },
      { id: "friends", label: "Con amici", funnyReaction: "Qualcosa che generi meme.", effects: fx({ boostTraits: { comedyLevel: 1, visualSpectacle: 1 }, boostMoods: ["funny", "action"] }) },
      { id: "distracted", label: "Con qualcuno che guarda il telefono ogni 5 minuti", funnyReaction: "Plot semplice o episodi brevi.", effects: fx({ boostTraits: { complexity: -2, comedyLevel: 1 }, hardFilters: { maxComplexity: "medium" } }) },
    ],
  },
  {
    id: "ending",
    category: "ending",
    text: "Che rapporto vuoi avere con il finale?",
    appliesTo: "both",
    priority: 6,
    maxAskOnce: true,
    discriminates: ["emotionalImpact"],
    options: [
      { id: "comfort", label: "Mi deve consolare", funnyReaction: "Lieto fine o rimborsi emotivi.", effects: fx({ boostTraits: { emotionalImpact: -1, comfortLevel: 1 }, boostMoods: ["cozy"] }) },
      { id: "bittersweet", label: "Va bene anche agrodolce", funnyReaction: "Emozioni mischiate.", effects: fx({ boostTraits: { emotionalImpact: 0 } }) },
      { id: "questions", label: "Mi può lasciare domande", funnyReaction: "Finale che alimenta teorie.", effects: fx({ boostTraits: { complexity: 1, mysteryLevel: 1 }, boostMoods: ["mind-bending"] }) },
      { id: "ruin", label: "Mi deve rovinare la settimana", funnyReaction: "Trauma narrativo incoming.", effects: fx({ boostTraits: { emotionalImpact: 2 }, boostMoods: ["sad", "dark"] }) },
    ],
  },
  {
    id: "binge-tv",
    category: "binge",
    text: "Quanto binge è la serata?",
    appliesTo: "tv",
    priority: 7,
    maxAskOnce: true,
    discriminates: ["bingeability"],
    options: [
      { id: "one", label: "Solo uno, giuro", funnyReaction: "Uno. Classic lie.", effects: fx({ boostTraits: { bingeability: -1 } }) },
      { id: "marathon", label: "Maratona fino alle 3", funnyReaction: "Cliffhanger addiction mode.", effects: fx({ boostTraits: { bingeability: 2 }, boostMoods: ["binge"], softFilters: { preferBinge: 3 } }) },
      { id: "background", label: "Sottofondo mentre faccio altro", funnyReaction: "Comedy o episodi brevi.", effects: fx({ boostTraits: { complexity: -2, comedyLevel: 1 }, boostMoods: ["cozy", "funny"] }) },
      { id: "weekend", label: "Weekend intero", funnyReaction: "Serie lunghe, zero rimpianti.", effects: fx({ boostTraits: { bingeability: 2, commitment: 1 } }) },
    ],
  },
  {
    id: "language",
    category: "language",
    text: "Sottotitoli: amici o nemici?",
    appliesTo: "both",
    priority: 5,
    maxAskOnce: true,
    discriminates: ["subtitleEffort"],
    options: [
      { id: "no-subs", label: "Niente sottotitoli, solo doppiaggio", funnyReaction: "Priorità a titoli facili da seguire.", effects: fx({ boostTraits: { subtitleEffort: -2 }, hardFilters: { maxSubtitleEffort: "low" } }) },
      { id: "subs-ok", label: "Sottotitoli ok", funnyReaction: "Più opzioni in gioco.", effects: fx({ boostTraits: { subtitleEffort: 0 } }) },
      { id: "original", label: "Voglio originale, anche se devo leggere", funnyReaction: "Purista del audio originale.", effects: fx({ boostTraits: { subtitleEffort: 1 } }) },
      { id: "whatever", label: "Non mi importa", funnyReaction: "La sfera decide per te.", effects: fx({}) },
    ],
  },
  {
    id: "romance",
    category: "genre",
    text: "Quanto romance sopporti?",
    appliesTo: "both",
    priority: 5,
    maxAskOnce: true,
    discriminates: ["romanceLevel"],
    options: [
      { id: "zero", label: "Zero, grazie", funnyReaction: "Niente meet-cute stasera.", effects: fx({ penalizeTraits: { romanceLevel: -2 }, hardFilters: { maxViolence: "high" } }) },
      { id: "side", label: "Sottotraccia va bene", funnyReaction: "Romance come condimento.", effects: fx({ boostTraits: { romanceLevel: 0 } }) },
      { id: "yes", label: "Voglio butterflies", funnyReaction: "Cuore in modalità flutter.", effects: fx({ boostTraits: { romanceLevel: 2 }, boostMoods: ["romantic"] }) },
      { id: "pain", label: "Amore che fa male", funnyReaction: "Romance drama incoming.", effects: fx({ boostTraits: { romanceLevel: 2, emotionalImpact: 2 }, boostMoods: ["sad", "romantic"] }) },
    ],
  },
  {
    id: "comedy-style",
    category: "mood",
    text: "Se ridi, come ridi?",
    appliesTo: "both",
    priority: 4,
    maxAskOnce: true,
    discriminates: ["comedyLevel"],
    options: [
      { id: "sitcom", label: "Sitcom e battute facili", funnyReaction: "Risate low-effort.", effects: fx({ boostTraits: { comedyLevel: 2, complexity: -1 }, boostMoods: ["funny", "cozy"] }) },
      { id: "dark-humor", label: "Umorismo nero", funnyReaction: "Ridere di cose sbagliate.", effects: fx({ boostTraits: { comedyLevel: 1, violenceLevel: 1 }, boostMoods: ["dark", "funny"] }) },
      { id: "smart", label: "Commedia intelligente", funnyReaction: "Battute per chi ha visto troppe sitcom.", effects: fx({ boostTraits: { comedyLevel: 1, complexity: 1 } }) },
      { id: "no-laugh", label: "Stasera non voglio ridere", funnyReaction: "Comedy off the table.", effects: fx({ penalizeTraits: { comedyLevel: -2 } }) },
    ],
  },
  {
    id: "horror",
    category: "violence",
    text: "Horror vero o solo brividi?",
    appliesTo: "both",
    priority: 6,
    maxAskOnce: true,
    discriminates: ["horrorLevel"],
    options: [
      { id: "none", label: "Zero horror", funnyReaction: "Niente demoni, nemmeno quelli carini.", effects: fx({ hardFilters: { maxHorror: "none" }, penalizeTraits: { horrorLevel: -2 } }) },
      { id: "mild", label: "Brividi soft", funnyReaction: "Tensione senza incubi.", effects: fx({ boostTraits: { horrorLevel: 0, mysteryLevel: 1 } }) },
      { id: "real", label: "Horror che conta", funnyReaction: "Luce accesa consigliata.", effects: fx({ boostTraits: { horrorLevel: 2 }, boostMoods: ["dark"] }) },
      { id: "gore", label: "Sangue e urla", funnyReaction: "La sfera ha visto troppi jump scare scarsi.", effects: fx({ boostTraits: { horrorLevel: 2, violenceLevel: 2 } }) },
    ],
  },
  {
    id: "complexity-deep",
    category: "complexity",
    text: "Quanto vuoi impegnarti mentalmente?",
    appliesTo: "both",
    priority: 7,
    maxAskOnce: true,
    discriminates: ["complexity"],
    options: [
      { id: "off", label: "Cervello spento", funnyReaction: "Modalità zombie.", effects: fx({ hardFilters: { maxComplexity: "easy" }, boostTraits: { complexity: -2 } }) },
      { id: "normal", label: "Trama normale", funnyReaction: "Seguibile senza wiki.", effects: fx({ boostTraits: { complexity: 0 } }) },
      { id: "deep", label: "Trame intrecciate", funnyReaction: "Appunti consigliati.", effects: fx({ boostTraits: { complexity: 2 }, boostMoods: ["mind-bending"] }) },
      { id: "wiki", label: "Voglio aprire Reddit a metà episodio", funnyReaction: "Lore da decifrare.", effects: fx({ boostTraits: { complexity: 2, mysteryLevel: 1 }, hardFilters: { minComplexity: "complex" } }) },
    ],
  },
  {
    id: "emotional-light",
    category: "emotionalImpact",
    text: "Quanto peso emotivo reggi?",
    appliesTo: "both",
    priority: 7,
    maxAskOnce: true,
    discriminates: ["emotionalImpact"],
    options: [
      { id: "feather", label: "Piuma, zero drama", funnyReaction: "Niente lacrime.", effects: fx({ hardFilters: { maxEmotional: "light" }, boostTraits: { emotionalImpact: -2 } }) },
      { id: "medium", label: "Un po' di cuore ci sta", funnyReaction: "Emozioni dosate.", effects: fx({ boostTraits: { emotionalImpact: 0 } }) },
      { id: "heavy", label: "Voglio sentire qualcosa", funnyReaction: "Cuore in modalità attiva.", effects: fx({ boostTraits: { emotionalImpact: 2 }, boostMoods: ["sad", "romantic"] }) },
      { id: "wreck", label: "Demoliscimi", funnyReaction: "Fazzoletti x2.", effects: fx({ boostTraits: { emotionalImpact: 2 }, hardFilters: { minEmotional: "heavy" } }) },
    ],
  },
  {
    id: "visual",
    category: "genre",
    text: "Quanto spettacolo visivo?",
    appliesTo: "both",
    priority: 4,
    maxAskOnce: true,
    discriminates: ["visualSpectacle"],
    options: [
      { id: "minimal", label: "Minimal, conta la storia", funnyReaction: "Budget basso, cuore grande.", effects: fx({ boostTraits: { visualSpectacle: -2 } }) },
      { id: "nice", label: "Bello da vedere", funnyReaction: "Estetica curata.", effects: fx({ boostTraits: { visualSpectacle: 1 } }) },
      { id: "epic", label: "Blockbuster vibes", funnyReaction: "Esplosioni optional.", effects: fx({ boostTraits: { visualSpectacle: 2 }, boostMoods: ["action", "epic"] }) },
      { id: "art", label: "Arte visiva, anche lento", funnyReaction: "Ogni frame un quadro.", effects: fx({ boostTraits: { visualSpectacle: 1, pace: -1 } }) },
    ],
  },
  {
    id: "genre-crime",
    category: "genre",
    text: "Crime e indagini ti attirano?",
    appliesTo: "both",
    priority: 4,
    maxAskOnce: true,
    discriminates: ["mysteryLevel"],
    options: [
      { id: "love", label: "Detective, indizi, colpevole", funnyReaction: "True crime energy.", effects: fx({ boostTraits: { mysteryLevel: 2 }, boostMoods: ["thriller"] }) },
      { id: "maybe", label: "Se non è troppo lento", funnyReaction: "Crime con ritmo.", effects: fx({ boostTraits: { mysteryLevel: 1, pace: 1 } }) },
      { id: "no", label: "No grazie", funnyReaction: "Crime off the table.", effects: fx({ penalizeMoods: ["thriller"], penalizeTraits: { mysteryLevel: -1 } }) },
      { id: "psych", label: "Thriller psicologico", funnyReaction: "Menti contorte incoming.", effects: fx({ boostTraits: { mysteryLevel: 2, complexity: 1 }, boostMoods: ["mind-bending", "thriller"] }) },
    ],
  },
  {
    id: "scifi-depth",
    category: "genre",
    text: "Sci-fi: popcorn o filosofia?",
    appliesTo: "both",
    priority: 4,
    maxAskOnce: true,
    discriminates: ["complexity", "mood"],
    options: [
      { id: "popcorn", label: "Laser e cose che esplodono", funnyReaction: "Sci-fi action.", effects: fx({ boostMoods: ["sci-fi", "action"], boostTraits: { pace: 1, visualSpectacle: 1 } }) },
      { id: "philosophy", label: "Coscienza, simulazioni, esistenza", funnyReaction: "Blade Runner vibes.", effects: fx({ boostMoods: ["sci-fi", "mind-bending"], boostTraits: { complexity: 2 } }) },
      { id: "no-sci", label: "Niente sci-fi", funnyReaction: "Terraferma only.", effects: fx({ penalizeMoods: ["sci-fi", "fantasy"] }) },
      { id: "dystopia", label: "Distopia che fa riflettere", funnyReaction: "Black Mirror energy.", effects: fx({ boostMoods: ["sci-fi", "dark", "mind-bending"], boostTraits: { emotionalImpact: 1 } }) },
    ],
  },
  {
    id: "animation",
    category: "genre",
    text: "Animazione: sì o no?",
    appliesTo: "both",
    priority: 3,
    maxAskOnce: true,
    discriminates: ["mood"],
    options: [
      { id: "yes-adult", label: "Animazione adulta ok", funnyReaction: "Non solo cartoni per bimbi.", effects: fx({ hardFilters: { requireGenres: ["Animation", "Animazione"] }, boostTraits: { complexity: 1 } }) },
      { id: "yes-all", label: "Tutto ok", funnyReaction: "Animazione benvenuta.", effects: fx({ boostMoods: ["cozy", "funny"] }) },
      { id: "no", label: "Preferisco live action", funnyReaction: "Solo attori in carne ed ossa.", effects: fx({ penalizeMoods: ["cozy"], hardFilters: { excludeGenres: ["Animation", "Animazione"] } }) },
      { id: "family", label: "Qualcosa per tutti", funnyReaction: "Family friendly.", effects: fx({ boostTraits: { comedyLevel: 1, violenceLevel: -2 }, hardFilters: { maxViolence: "low" } }) },
    ],
  },
  {
    id: "docu",
    category: "genre",
    text: "Documentari stasera?",
    appliesTo: "both",
    priority: 2,
    maxAskOnce: true,
    discriminates: ["mood"],
    options: [
      { id: "yes", label: "Voglio imparare qualcosa", funnyReaction: "Cervello in modalità curiosa.", effects: fx({ hardFilters: { requireGenres: ["Documentary", "Documentario"] }, boostTraits: { complexity: 1, pace: -1 } }) },
      { id: "no", label: "No, voglio fiction", funnyReaction: "Niente realtà stasera.", effects: fx({ hardFilters: { excludeGenres: ["Documentary", "Documentario"] } }) },
      { id: "maybe", label: "Docu-drama ok", funnyReaction: "Mezzo vero, mezzo inventato.", effects: fx({ boostTraits: { emotionalImpact: 1 } }) },
      { id: "true-crime", label: "True crime (ma non troppo pesante)", funnyReaction: "Crimini reali, ansia controllata.", effects: fx({ boostTraits: { mysteryLevel: 1 }, hardFilters: { maxViolence: "medium" } }) },
    ],
  },
  {
    id: "nostalgia",
    category: "comfort",
    text: "Nostalgia o novità?",
    appliesTo: "both",
    priority: 4,
    maxAskOnce: true,
    discriminates: ["mainstreamLevel", "comfortLevel"],
    options: [
      { id: "classic", label: "Classici che non invecchiano", funnyReaction: "Icone del passato.", effects: fx({ boostMoods: ["iconic"], boostTraits: { mainstreamLevel: 1, comfortLevel: 2 } }) },
      { id: "recent", label: "Uscite recenti", funnyReaction: "Solo roba fresca.", effects: fx({ boostTraits: { mainstreamLevel: 0 } }) },
      { id: "new", label: "Mai sentito nominare", funnyReaction: "Chicca assoluta.", effects: fx({ boostTraits: { mainstreamLevel: -2 }, boostMoods: ["hidden-gem"] }) },
      { id: "mix", label: "Mix di tutto", funnyReaction: "Sorpresa totale.", effects: fx({}) },
    ],
  },
  {
    id: "violence-tv",
    category: "violence",
    text: "Sangue in TV: che livello?",
    appliesTo: "both",
    priority: 5,
    maxAskOnce: true,
    discriminates: ["violenceLevel"],
    options: [
      { id: "zero", label: "Famiglia-friendly", funnyReaction: "Niente rosso sullo schermo.", effects: fx({ hardFilters: { maxViolence: "none" } }) },
      { id: "pg13", label: "PG-13 va bene", funnyReaction: "Violenza soft.", effects: fx({ hardFilters: { maxViolence: "medium" } }) },
      { id: "mature", label: "Mature content ok", funnyReaction: "Game of Thrones zone.", effects: fx({ boostTraits: { violenceLevel: 1 } }) },
      { id: "extreme", label: "Niente limiti", funnyReaction: "La sfera non guarda.", effects: fx({ boostTraits: { violenceLevel: 2 } }) },
    ],
  },
  {
    id: "twist",
    category: "ending",
    text: "Colpi di scena: quanti ne vuoi?",
    appliesTo: "both",
    priority: 5,
    maxAskOnce: true,
    discriminates: ["mysteryLevel", "complexity"],
    options: [
      { id: "predictable", label: "Prevedibile va bene", funnyReaction: "Comfort plot.", effects: fx({ boostTraits: { complexity: -1, mysteryLevel: -1 } }) },
      { id: "some", label: "Qualche twist", funnyReaction: "Sorpresa dosata.", effects: fx({ boostTraits: { mysteryLevel: 1 } }) },
      { id: "many", label: "Twist ogni 10 minuti", funnyReaction: "Whiplash narrativo.", effects: fx({ boostTraits: { mysteryLevel: 2, pace: 1 }, boostMoods: ["mind-bending"] }) },
      { id: "unreliable", label: "Narratore inaffidabile", funnyReaction: "Non fidarti di niente.", effects: fx({ boostTraits: { complexity: 2, mysteryLevel: 2 }, boostMoods: ["mind-bending", "thriller"] }) },
    ],
  },
  {
    id: "music",
    category: "mood",
    text: "Musical o colonne sonore iconiche?",
    appliesTo: "both",
    priority: 2,
    maxAskOnce: true,
    discriminates: ["mood"],
    options: [
      { id: "musical", label: "Persone che cantano", funnyReaction: "Break into song.", effects: fx({ hardFilters: { requireGenres: ["Music"] }, boostTraits: { comedyLevel: 1 } }) },
      { id: "soundtrack", label: "Bella colonna sonora basta", funnyReaction: "Audio che fa il lavoro.", effects: fx({ boostTraits: { visualSpectacle: 1 } }) },
      { id: "no", label: "Niente musical", funnyReaction: "Zero jazz hands.", effects: fx({ hardFilters: { excludeGenres: ["Music"] } }) },
      { id: "whatever", label: "Non mi importa", funnyReaction: "Ok.", effects: fx({}) },
    ],
  },
];

export const NERDACOLO_QUESTION_BY_ID = Object.fromEntries(
  NERDACOLO_QUESTIONS.map(q => [q.id, q]),
) as Record<string, NerdacoloQuestion>;

export function questionsForMode(mode: "movie" | "tv" | "surprise"): NerdacoloQuestion[] {
  return NERDACOLO_QUESTIONS.filter(q => {
    if (q.appliesTo === "both") return true;
    if (mode === "surprise") return true;
    return q.appliesTo === mode;
  });
}
