/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as AuthenticatedWatchlistRouteImport } from './routes/_authenticated/watchlist'
import { Route as AuthenticatedStatisticheRouteImport } from './routes/_authenticated/statistiche'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedProssimiRouteImport } from './routes/_authenticated/prossimi'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPremiumRouteImport } from './routes/_authenticated/premium'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNerdacoloRouteImport } from './routes/_authenticated/nerdacolo'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedGruppoRouteImport } from './routes/_authenticated/gruppo'
import { Route as AuthenticatedDubbioRouteImport } from './routes/_authenticated/dubbio'
import { Route as AuthenticatedDaTvtimeRouteImport } from './routes/_authenticated/da-tvtime'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAmiciRouteImport } from './routes/_authenticated/amici'
import { Route as AuthenticatedProfiloSerieRouteImport } from './routes/_authenticated/profilo.serie'
import { Route as AuthenticatedProfiloFilmRouteImport } from './routes/_authenticated/profilo.film'
import { Route as AuthenticatedPersonIdRouteImport } from './routes/_authenticated/person.$id'
import { Route as AuthenticatedDubbioRisultatoRouteImport } from './routes/_authenticated/dubbio.risultato'
import { Route as AuthenticatedMediaTypeIdRouteImport } from './routes/_authenticated/media.$type.$id'
import { Route as AuthenticatedEpisodeIdSeasonEpisodeRouteImport } from './routes/_authenticated/episode.$id.$season.$episode'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWatchlistRoute = AuthenticatedWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatisticheRoute =
  AuthenticatedStatisticheRouteImport.update({
    id: '/statistiche',
    path: '/statistiche',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProssimiRoute = AuthenticatedProssimiRouteImport.update({
  id: '/prossimi',
  path: '/prossimi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPremiumRoute = AuthenticatedPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNerdacoloRoute = AuthenticatedNerdacoloRouteImport.update({
  id: '/nerdacolo',
  path: '/nerdacolo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGruppoRoute = AuthenticatedGruppoRouteImport.update({
  id: '/gruppo',
  path: '/gruppo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDubbioRoute = AuthenticatedDubbioRouteImport.update({
  id: '/dubbio',
  path: '/dubbio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDaTvtimeRoute = AuthenticatedDaTvtimeRouteImport.update({
  id: '/da-tvtime',
  path: '/da-tvtime',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAmiciRoute = AuthenticatedAmiciRouteImport.update({
  id: '/amici',
  path: '/amici',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfiloSerieRoute =
  AuthenticatedProfiloSerieRouteImport.update({
    id: '/profilo/serie',
    path: '/profilo/serie',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfiloFilmRoute =
  AuthenticatedProfiloFilmRouteImport.update({
    id: '/profilo/film',
    path: '/profilo/film',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPersonIdRoute = AuthenticatedPersonIdRouteImport.update({
  id: '/person/$id',
  path: '/person/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDubbioRisultatoRoute =
  AuthenticatedDubbioRisultatoRouteImport.update({
    id: '/risultato',
    path: '/risultato',
    getParentRoute: () => AuthenticatedDubbioRoute,
  } as any)
const AuthenticatedMediaTypeIdRoute =
  AuthenticatedMediaTypeIdRouteImport.update({
    id: '/media/$type/$id',
    path: '/media/$type/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEpisodeIdSeasonEpisodeRoute =
  AuthenticatedEpisodeIdSeasonEpisodeRouteImport.update({
    id: '/episode/$id/$season/$episode',
    path: '/episode/$id/$season/$episode',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/amici': typeof AuthenticatedAmiciRoute
  '/app': typeof AuthenticatedAppRoute
  '/da-tvtime': typeof AuthenticatedDaTvtimeRoute
  '/dubbio': typeof AuthenticatedDubbioRouteWithChildren
  '/gruppo': typeof AuthenticatedGruppoRoute
  '/import': typeof AuthenticatedImportRoute
  '/nerdacolo': typeof AuthenticatedNerdacoloRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/prossimi': typeof AuthenticatedProssimiRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/statistiche': typeof AuthenticatedStatisticheRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/u/$handle': typeof UHandleRoute
  '/dubbio/risultato': typeof AuthenticatedDubbioRisultatoRoute
  '/person/$id': typeof AuthenticatedPersonIdRoute
  '/profilo/film': typeof AuthenticatedProfiloFilmRoute
  '/profilo/serie': typeof AuthenticatedProfiloSerieRoute
  '/media/$type/$id': typeof AuthenticatedMediaTypeIdRoute
  '/episode/$id/$season/$episode': typeof AuthenticatedEpisodeIdSeasonEpisodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/amici': typeof AuthenticatedAmiciRoute
  '/app': typeof AuthenticatedAppRoute
  '/da-tvtime': typeof AuthenticatedDaTvtimeRoute
  '/dubbio': typeof AuthenticatedDubbioRouteWithChildren
  '/gruppo': typeof AuthenticatedGruppoRoute
  '/import': typeof AuthenticatedImportRoute
  '/nerdacolo': typeof AuthenticatedNerdacoloRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/prossimi': typeof AuthenticatedProssimiRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/statistiche': typeof AuthenticatedStatisticheRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/u/$handle': typeof UHandleRoute
  '/dubbio/risultato': typeof AuthenticatedDubbioRisultatoRoute
  '/person/$id': typeof AuthenticatedPersonIdRoute
  '/profilo/film': typeof AuthenticatedProfiloFilmRoute
  '/profilo/serie': typeof AuthenticatedProfiloSerieRoute
  '/media/$type/$id': typeof AuthenticatedMediaTypeIdRoute
  '/episode/$id/$season/$episode': typeof AuthenticatedEpisodeIdSeasonEpisodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/amici': typeof AuthenticatedAmiciRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/da-tvtime': typeof AuthenticatedDaTvtimeRoute
  '/_authenticated/dubbio': typeof AuthenticatedDubbioRouteWithChildren
  '/_authenticated/gruppo': typeof AuthenticatedGruppoRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/nerdacolo': typeof AuthenticatedNerdacoloRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/premium': typeof AuthenticatedPremiumRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/prossimi': typeof AuthenticatedProssimiRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/statistiche': typeof AuthenticatedStatisticheRoute
  '/_authenticated/watchlist': typeof AuthenticatedWatchlistRoute
  '/u/$handle': typeof UHandleRoute
  '/_authenticated/dubbio/risultato': typeof AuthenticatedDubbioRisultatoRoute
  '/_authenticated/person/$id': typeof AuthenticatedPersonIdRoute
  '/_authenticated/profilo/film': typeof AuthenticatedProfiloFilmRoute
  '/_authenticated/profilo/serie': typeof AuthenticatedProfiloSerieRoute
  '/_authenticated/media/$type/$id': typeof AuthenticatedMediaTypeIdRoute
  '/_authenticated/episode/$id/$season/$episode': typeof AuthenticatedEpisodeIdSeasonEpisodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/amici'
    | '/app'
    | '/da-tvtime'
    | '/dubbio'
    | '/gruppo'
    | '/import'
    | '/nerdacolo'
    | '/onboarding'
    | '/premium'
    | '/profile'
    | '/prossimi'
    | '/search'
    | '/settings'
    | '/statistiche'
    | '/watchlist'
    | '/u/$handle'
    | '/dubbio/risultato'
    | '/person/$id'
    | '/profilo/film'
    | '/profilo/serie'
    | '/media/$type/$id'
    | '/episode/$id/$season/$episode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/amici'
    | '/app'
    | '/da-tvtime'
    | '/dubbio'
    | '/gruppo'
    | '/import'
    | '/nerdacolo'
    | '/onboarding'
    | '/premium'
    | '/profile'
    | '/prossimi'
    | '/search'
    | '/settings'
    | '/statistiche'
    | '/watchlist'
    | '/u/$handle'
    | '/dubbio/risultato'
    | '/person/$id'
    | '/profilo/film'
    | '/profilo/serie'
    | '/media/$type/$id'
    | '/episode/$id/$season/$episode'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/amici'
    | '/_authenticated/app'
    | '/_authenticated/da-tvtime'
    | '/_authenticated/dubbio'
    | '/_authenticated/gruppo'
    | '/_authenticated/import'
    | '/_authenticated/nerdacolo'
    | '/_authenticated/onboarding'
    | '/_authenticated/premium'
    | '/_authenticated/profile'
    | '/_authenticated/prossimi'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/statistiche'
    | '/_authenticated/watchlist'
    | '/u/$handle'
    | '/_authenticated/dubbio/risultato'
    | '/_authenticated/person/$id'
    | '/_authenticated/profilo/film'
    | '/_authenticated/profilo/serie'
    | '/_authenticated/media/$type/$id'
    | '/_authenticated/episode/$id/$season/$episode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UHandleRoute: typeof UHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/watchlist': {
      id: '/_authenticated/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AuthenticatedWatchlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistiche': {
      id: '/_authenticated/statistiche'
      path: '/statistiche'
      fullPath: '/statistiche'
      preLoaderRoute: typeof AuthenticatedStatisticheRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prossimi': {
      id: '/_authenticated/prossimi'
      path: '/prossimi'
      fullPath: '/prossimi'
      preLoaderRoute: typeof AuthenticatedProssimiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/premium': {
      id: '/_authenticated/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedPremiumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nerdacolo': {
      id: '/_authenticated/nerdacolo'
      path: '/nerdacolo'
      fullPath: '/nerdacolo'
      preLoaderRoute: typeof AuthenticatedNerdacoloRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gruppo': {
      id: '/_authenticated/gruppo'
      path: '/gruppo'
      fullPath: '/gruppo'
      preLoaderRoute: typeof AuthenticatedGruppoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dubbio': {
      id: '/_authenticated/dubbio'
      path: '/dubbio'
      fullPath: '/dubbio'
      preLoaderRoute: typeof AuthenticatedDubbioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/da-tvtime': {
      id: '/_authenticated/da-tvtime'
      path: '/da-tvtime'
      fullPath: '/da-tvtime'
      preLoaderRoute: typeof AuthenticatedDaTvtimeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/amici': {
      id: '/_authenticated/amici'
      path: '/amici'
      fullPath: '/amici'
      preLoaderRoute: typeof AuthenticatedAmiciRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profilo/serie': {
      id: '/_authenticated/profilo/serie'
      path: '/profilo/serie'
      fullPath: '/profilo/serie'
      preLoaderRoute: typeof AuthenticatedProfiloSerieRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profilo/film': {
      id: '/_authenticated/profilo/film'
      path: '/profilo/film'
      fullPath: '/profilo/film'
      preLoaderRoute: typeof AuthenticatedProfiloFilmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/person/$id': {
      id: '/_authenticated/person/$id'
      path: '/person/$id'
      fullPath: '/person/$id'
      preLoaderRoute: typeof AuthenticatedPersonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dubbio/risultato': {
      id: '/_authenticated/dubbio/risultato'
      path: '/risultato'
      fullPath: '/dubbio/risultato'
      preLoaderRoute: typeof AuthenticatedDubbioRisultatoRouteImport
      parentRoute: typeof AuthenticatedDubbioRoute
    }
    '/_authenticated/media/$type/$id': {
      id: '/_authenticated/media/$type/$id'
      path: '/media/$type/$id'
      fullPath: '/media/$type/$id'
      preLoaderRoute: typeof AuthenticatedMediaTypeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/episode/$id/$season/$episode': {
      id: '/_authenticated/episode/$id/$season/$episode'
      path: '/episode/$id/$season/$episode'
      fullPath: '/episode/$id/$season/$episode'
      preLoaderRoute: typeof AuthenticatedEpisodeIdSeasonEpisodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedDubbioRouteChildren {
  AuthenticatedDubbioRisultatoRoute: typeof AuthenticatedDubbioRisultatoRoute
}

const AuthenticatedDubbioRouteChildren: AuthenticatedDubbioRouteChildren = {
  AuthenticatedDubbioRisultatoRoute: AuthenticatedDubbioRisultatoRoute,
}

const AuthenticatedDubbioRouteWithChildren =
  AuthenticatedDubbioRoute._addFileChildren(AuthenticatedDubbioRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAmiciRoute: typeof AuthenticatedAmiciRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedDaTvtimeRoute: typeof AuthenticatedDaTvtimeRoute
  AuthenticatedDubbioRoute: typeof AuthenticatedDubbioRouteWithChildren
  AuthenticatedGruppoRoute: typeof AuthenticatedGruppoRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedNerdacoloRoute: typeof AuthenticatedNerdacoloRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPremiumRoute: typeof AuthenticatedPremiumRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProssimiRoute: typeof AuthenticatedProssimiRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStatisticheRoute: typeof AuthenticatedStatisticheRoute
  AuthenticatedWatchlistRoute: typeof AuthenticatedWatchlistRoute
  AuthenticatedPersonIdRoute: typeof AuthenticatedPersonIdRoute
  AuthenticatedProfiloFilmRoute: typeof AuthenticatedProfiloFilmRoute
  AuthenticatedProfiloSerieRoute: typeof AuthenticatedProfiloSerieRoute
  AuthenticatedMediaTypeIdRoute: typeof AuthenticatedMediaTypeIdRoute
  AuthenticatedEpisodeIdSeasonEpisodeRoute: typeof AuthenticatedEpisodeIdSeasonEpisodeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAmiciRoute: AuthenticatedAmiciRoute,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedDaTvtimeRoute: AuthenticatedDaTvtimeRoute,
  AuthenticatedDubbioRoute: AuthenticatedDubbioRouteWithChildren,
  AuthenticatedGruppoRoute: AuthenticatedGruppoRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedNerdacoloRoute: AuthenticatedNerdacoloRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPremiumRoute: AuthenticatedPremiumRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProssimiRoute: AuthenticatedProssimiRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStatisticheRoute: AuthenticatedStatisticheRoute,
  AuthenticatedWatchlistRoute: AuthenticatedWatchlistRoute,
  AuthenticatedPersonIdRoute: AuthenticatedPersonIdRoute,
  AuthenticatedProfiloFilmRoute: AuthenticatedProfiloFilmRoute,
  AuthenticatedProfiloSerieRoute: AuthenticatedProfiloSerieRoute,
  AuthenticatedMediaTypeIdRoute: AuthenticatedMediaTypeIdRoute,
  AuthenticatedEpisodeIdSeasonEpisodeRoute: AuthenticatedEpisodeIdSeasonEpisodeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UHandleRoute: UHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
